version: '3.5'

services:
  api01:
    build:
      context: .
      dockerfile: Dockerfile.native
    hostname: api01
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  api02:
    build:
      context: .
      dockerfile: Dockerfile.native
    hostname: api02
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c log_min_messages=panic -c log_min_error_statement=panic
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.8GB'
